services:
  - type: web
    name: stockwellness
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 4 --timeout 120 app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: NEWS_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
    disk:
      name: cache
      mountPath: /opt/render/project/src/cache
      sizeGB: 1 